# docker-compose.yml

version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: sansthe 
    volumes:
      - ./data/rendezvous.sql:/docker-entrypoint-initdb.d/rendezvous.sql
      - ./data/user.sql:/docker-entrypoint-initdb.d/user.sql
    ports:
      - "3308:3306" 
    networks:
      - webnet

  web:
    build: .
    depends_on:
      - mysql
    ports:
      - "81:80" 
    networks:
      - webnet
    volumes:
      - .:/var/www/html 

networks:
  webnet:
    driver: bridge
